import { defineConfig } from "tsup";

/**
 * Same reasoning as `packages/cli/tsup.config.ts`: `@picx/core` and
 * `@picx/tools` are private workspace packages that would publish as
 * unresolvable `3.0.0` dependencies, so they are inlined here instead.
 *
 * `@modelcontextprotocol/server` and `zod` stay external and declared. Bundling
 * the MCP SDK would be actively wrong — a client and server that each carry
 * their own copy of the protocol types can disagree about them, and zod in
 * particular must be a single instance for schema identity to hold.
 */
export default defineConfig({
  entry: ["src/server.ts", "src/stdio.ts"],
  format: ["esm"],
  target: "node20",
  platform: "node",
  clean: true,
  // `createPicxMcpServer` is importable, so declarations are worth shipping.
  // Generated by tsc into a separate step if this proves flaky — see below.
  dts: false,
  noExternal: ["@picx/core", "@picx/tools"],
  external: ["@modelcontextprotocol/server", "zod", "picx-ai"],
});
